services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio_dev
      POSTGRES_DB: portfolio_db
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
